//! Documentation generator for Canister.
//!
//! Extracts structured information from Rust code and generates Markdown
//! files for the static documentation site. This is the translation layer
//! between the Rust source of truth and the mdBook presentation layer.
//!
//! Usage:
//!   can-docgen [--out-dir docs/src/generated]
//!
//! Generated files:
//!   - config.md     — Config reference from JSON Schema
//!   - manifest.md   — canister.toml reference from JSON Schema
//!   - recipes.md    — Built-in recipe contents
//!   - merge.md      — Merge semantics table
//!   - cli.md        — CLI reference (from running `can --help`)

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use schemars::schema::{InstanceType, Metadata, Schema, SchemaObject, SingleOrVec};

fn main() -> Result<()> {
    let out_dir = std::env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("docs/src/generated"));

    std::fs::create_dir_all(&out_dir)?;

    generate_config_reference(&out_dir)?;
    generate_manifest_reference(&out_dir)?;
    generate_merge_semantics(&out_dir)?;
    generate_builtin_recipes(&out_dir)?;
    generate_cli_reference(&out_dir)?;

    eprintln!("Documentation generated in {}", out_dir.display());
    Ok(())
}

// ---------------------------------------------------------------------------
// Config reference (from JSON Schema)
// ---------------------------------------------------------------------------

fn generate_config_reference(out_dir: &Path) -> Result<()> {
    let schema = schemars::schema_for!(can_policy::RecipeFile);
    let mut out = String::new();

    out.push_str("# Configuration Reference\n\n");
    out.push_str("> **This file is auto-generated by `can-docgen`.** Do not edit manually.\n\n");
    out.push_str("Canister uses TOML recipe files with strict schema validation. ");
    out.push_str("Unknown fields are rejected at parse time.\n\n");

    render_root_schema(&schema, &mut out)?;

    std::fs::write(out_dir.join("config.md"), &out)?;
    eprintln!("  Generated config.md");
    Ok(())
}

fn generate_manifest_reference(out_dir: &Path) -> Result<()> {
    let schema = schemars::schema_for!(can_policy::Manifest);
    let mut out = String::new();

    out.push_str("# Manifest Reference (`canister.toml`)\n\n");
    out.push_str("> **This file is auto-generated by `can-docgen`.** Do not edit manually.\n\n");
    out.push_str("A project manifest declares named sandboxes. Place `canister.toml` in your project root.\n\n");

    render_root_schema(&schema, &mut out)?;

    std::fs::write(out_dir.join("manifest.md"), &out)?;
    eprintln!("  Generated manifest.md");
    Ok(())
}

fn render_root_schema(root: &schemars::schema::RootSchema, out: &mut String) -> Result<()> {
    render_object_section(&root.schema, &root.definitions, out, "", 2)
}

/// Render an object schema as a section with a field table,
/// then recurse into nested object fields as sub-sections.
fn render_object_section(
    schema: &SchemaObject,
    definitions: &BTreeMap<String, Schema>,
    out: &mut String,
    toml_path: &str,
    heading_depth: usize,
) -> Result<()> {
    let schema = resolve_schema_object(schema, definitions);
    let obj = match &schema.object {
        Some(obj) => obj,
        None => return Ok(()),
    };

    // Section heading
    let heading = "#".repeat(heading_depth);
    if toml_path.is_empty() {
        out.push_str(&format!("{heading} Top-level fields\n\n"));
    } else {
        out.push_str(&format!("{heading} `[{toml_path}]`\n\n"));
    }

    // Section description from schema metadata
    let desc = description_from_metadata(&schema.metadata);
    if !desc.is_empty() {
        out.push_str(&desc);
        out.push_str("\n\n");
    }

    // Separate leaf fields from nested object sections
    let mut leaf_fields: Vec<(&String, &SchemaObject)> = Vec::new();
    let mut nested_sections: Vec<(&String, &SchemaObject)> = Vec::new();

    for (name, prop) in &obj.properties {
        if let Schema::Object(prop_schema) = prop {
            let resolved = resolve_schema_object(prop_schema, definitions);
            // It's a nested section if the resolved schema has object properties
            if let Some(ref inner_obj) = resolved.object {
                if !inner_obj.properties.is_empty() {
                    nested_sections.push((name, prop_schema));
                    continue;
                }
            }
            leaf_fields.push((name, prop_schema));
        }
    }

    // Render field table
    if !leaf_fields.is_empty() {
        out.push_str("| Field | Type | Default | Description |\n");
        out.push_str("|-------|------|---------|-------------|\n");

        for (name, prop_schema) in &leaf_fields {
            let resolved = resolve_schema_object(prop_schema, definitions);
            let ty = type_name(prop_schema, definitions);
            let desc = description_from_metadata(&resolved.metadata);
            let def = default_value(&resolved.metadata);
            out.push_str(&format!("| `{name}` | {ty} | {def} | {desc} |\n"));
        }
        out.push('\n');
    }

    // Recurse into nested sections
    for (name, prop_schema) in &nested_sections {
        let child_path = if toml_path.is_empty() {
            name.to_string()
        } else {
            format!("{toml_path}.{name}")
        };
        render_object_section(
            prop_schema,
            definitions,
            out,
            &child_path,
            heading_depth + 1,
        )?;
    }

    Ok(())
}

fn resolve_ref<'a>(
    reference: &str,
    definitions: &'a BTreeMap<String, Schema>,
) -> Option<&'a SchemaObject> {
    let name = reference.strip_prefix("#/definitions/")?;
    match definitions.get(name)? {
        Schema::Object(obj) => Some(obj),
        _ => None,
    }
}

fn resolve_schema_object<'a>(
    schema: &'a SchemaObject,
    definitions: &'a BTreeMap<String, Schema>,
) -> &'a SchemaObject {
    // Direct $ref
    if let Some(ref reference) = schema.reference {
        return resolve_ref(reference, definitions).unwrap_or(schema);
    }
    // allOf with single $ref (schemars pattern for fields with defaults)
    if let Some(ref subschemas) = schema.subschemas {
        if let Some(ref all_of) = subschemas.all_of {
            if all_of.len() == 1 {
                if let Schema::Object(inner) = &all_of[0] {
                    if let Some(ref reference) = inner.reference {
                        return resolve_ref(reference, definitions).unwrap_or(schema);
                    }
                }
            }
        }
        // anyOf with $ref + null (nullable pattern)
        if let Some(ref any_of) = subschemas.any_of {
            for variant in any_of {
                if let Schema::Object(inner) = variant {
                    if let Some(ref reference) = inner.reference {
                        return resolve_ref(reference, definitions).unwrap_or(schema);
                    }
                }
            }
        }
    }
    schema
}

fn type_name(schema: &SchemaObject, definitions: &BTreeMap<String, Schema>) -> String {
    // Check nullable wrapper BEFORE resolving (anyOf with null)
    if let Some(ref subschemas) = schema.subschemas {
        if let Some(ref any_of) = subschemas.any_of {
            let non_null: Vec<_> = any_of
                .iter()
                .filter(|s| {
                    !matches!(s, Schema::Object(obj) if obj.instance_type == Some(SingleOrVec::Single(Box::new(InstanceType::Null))))
                })
                .collect();
            if non_null.len() == 1 {
                if let Schema::Object(inner) = &non_null[0] {
                    return format!("{} (optional)", type_name(inner, definitions));
                }
            }
        }
        // allOf with single $ref (schemars default pattern)
        if let Some(ref all_of) = subschemas.all_of {
            if all_of.len() == 1 {
                if let Schema::Object(inner) = &all_of[0] {
                    return type_name(inner, definitions);
                }
            }
        }
    }

    // Handle multi-type (e.g., ["boolean", "null"])
    if let Some(SingleOrVec::Vec(ref types)) = schema.instance_type {
        let non_null: Vec<_> = types.iter().filter(|t| **t != InstanceType::Null).collect();
        if non_null.len() == 1 {
            let type_str = match non_null[0] {
                InstanceType::String => "string",
                InstanceType::Integer => "integer",
                InstanceType::Number => "number",
                InstanceType::Boolean => "bool",
                _ => "any",
            };
            return format!("{type_str} (optional)");
        }
    }

    let schema = resolve_schema_object(schema, definitions);

    // Check for enum variants (oneOf)
    if let Some(ref subschemas) = schema.subschemas {
        if let Some(ref one_of) = subschemas.one_of {
            let variants: Vec<String> = one_of
                .iter()
                .filter_map(|s| match s {
                    Schema::Object(obj) => {
                        if let Some(ref e) = obj.enum_values {
                            Some(
                                e.iter()
                                    .map(|v| format!("`{}`", v.as_str().unwrap_or("?")))
                                    .collect::<Vec<_>>()
                                    .join(", "),
                            )
                        } else {
                            Some(type_name(obj, definitions))
                        }
                    }
                    _ => None,
                })
                .collect();
            if !variants.is_empty() {
                return variants.join(" \\| ");
            }
        }
    }

    // Check for enum values directly
    if let Some(ref e) = schema.enum_values {
        return e
            .iter()
            .map(|v| format!("`\"{}\"`", v.as_str().unwrap_or("?")))
            .collect::<Vec<_>>()
            .join(", ");
    }

    match &schema.instance_type {
        Some(SingleOrVec::Single(t)) => match **t {
            InstanceType::String => "string".to_string(),
            InstanceType::Integer => "integer".to_string(),
            InstanceType::Number => "number".to_string(),
            InstanceType::Boolean => "bool".to_string(),
            InstanceType::Array => {
                if let Some(ref arr) = schema.array {
                    if let Some(Schema::Object(items)) = arr.items.as_ref().and_then(|i| match i {
                        SingleOrVec::Single(s) => Some(s.as_ref()),
                        _ => None,
                    }) {
                        format!("{}[]", type_name(items, definitions))
                    } else {
                        "array".to_string()
                    }
                } else {
                    "array".to_string()
                }
            }
            InstanceType::Object => "object".to_string(),
            InstanceType::Null => "null".to_string(),
        },
        _ => {
            // Check if it's a $ref
            if let Some(ref reference) = schema.reference {
                reference
                    .strip_prefix("#/definitions/")
                    .unwrap_or(reference)
                    .to_string()
            } else {
                "any".to_string()
            }
        }
    }
}

fn description_from_metadata(metadata: &Option<Box<Metadata>>) -> String {
    metadata
        .as_ref()
        .and_then(|m| m.description.as_ref())
        .map(|d| {
            // Take first paragraph only for table display
            d.split("\n\n")
                .next()
                .unwrap_or(d)
                .lines()
                .collect::<Vec<_>>()
                .join(" ")
        })
        .unwrap_or_default()
}

fn default_value(metadata: &Option<Box<Metadata>>) -> String {
    metadata
        .as_ref()
        .and_then(|m| m.default.as_ref())
        .map(|d| {
            if d.is_null() {
                "—".to_string()
            } else if let Some(s) = d.as_str() {
                if s.is_empty() {
                    "—".to_string()
                } else {
                    format!("`\"{s}\"`")
                }
            } else if let Some(arr) = d.as_array() {
                if arr.is_empty() {
                    "`[]`".to_string()
                } else {
                    format!("`{d}`")
                }
            } else if let Some(b) = d.as_bool() {
                format!("`{b}`")
            } else {
                format!("`{d}`")
            }
        })
        .unwrap_or_else(|| "—".to_string())
}

// ---------------------------------------------------------------------------
// Merge semantics
// ---------------------------------------------------------------------------

fn generate_merge_semantics(out_dir: &Path) -> Result<()> {
    let mut out = String::new();
    out.push_str("# Merge Semantics\n\n");
    out.push_str("> **This file is auto-generated by `can-docgen`.** Do not edit manually.\n\n");
    out.push_str(
        "When multiple recipes are composed, each field follows a specific merge strategy.\n\n",
    );
    out.push_str("## Composition Order\n\n");
    out.push_str("```\n");
    out.push_str("base.toml (always loaded first)\n");
    out.push_str("  → auto-detected recipes (match_prefix against command binary)\n");
    out.push_str("  → explicit --recipe args (left to right)\n");
    out.push_str("  → manifest overrides (for `can up`)\n");
    out.push_str("  = final SandboxConfig\n");
    out.push_str("```\n\n");
    out.push_str("## Field Merge Strategies\n\n");
    out.push_str("| Field | Type | Strategy | Description |\n");
    out.push_str("|-------|------|----------|-------------|\n");

    // These are encoded from the merge() implementation in config.rs
    let rows = [
        (
            "recipe",
            "RecipeMeta",
            "Overlay",
            "Later recipe's metadata wins if present",
        ),
        (
            "strict",
            "Option<bool>",
            "OR",
            "Any `Some(true)` wins — can never be loosened",
        ),
        (
            "filesystem.allow",
            "Vec<PathBuf>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "filesystem.allow_write",
            "Vec<PathBuf>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "filesystem.deny",
            "Vec<PathBuf>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "filesystem.mask",
            "Vec<PathBuf>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "network.allow_domains",
            "Vec<String>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "network.allow_ips",
            "Vec<String>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "network.deny_all",
            "Option<bool>",
            "Last-Some-wins",
            "`None` preserves earlier value; `Some(x)` overwrites",
        ),
        (
            "network.ports",
            "Vec<PortMapping>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "process.max_pids",
            "Option<u32>",
            "Last-Some-wins",
            "`None` preserves earlier value; `Some(x)` overwrites",
        ),
        (
            "process.allow_execve",
            "Vec<PathBuf>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "process.env_passthrough",
            "Vec<String>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "resources.memory_mb",
            "Option<u64>",
            "Last-Some-wins",
            "`None` preserves earlier value; `Some(x)` overwrites",
        ),
        (
            "resources.cpu_percent",
            "Option<u32>",
            "Last-Some-wins",
            "`None` preserves earlier value; `Some(x)` overwrites",
        ),
        (
            "syscalls.seccomp_mode",
            "Option<SeccompMode>",
            "Last-Some-wins",
            "`None` preserves earlier value; `Some(x)` overwrites",
        ),
        (
            "syscalls.notifier",
            "Option<bool>",
            "Last-Some-wins",
            "`None` preserves earlier value; `Some(x)` overwrites",
        ),
        (
            "syscalls.allow",
            "Vec<String>",
            "Union",
            "Absolute allow list (baseline only)",
        ),
        (
            "syscalls.deny",
            "Vec<String>",
            "Union",
            "Absolute deny list (baseline only)",
        ),
        (
            "syscalls.allow_extra",
            "Vec<String>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
        (
            "syscalls.deny_extra",
            "Vec<String>",
            "Union",
            "Deduplicated, preserving first-occurrence order",
        ),
    ];

    for (field, ty, strategy, desc) in &rows {
        out.push_str(&format!(
            "| `{field}` | `{ty}` | **{strategy}** | {desc} |\n"
        ));
    }

    out.push_str("\n### Strategy Definitions\n\n");
    out.push_str("- **Union**: Both base and overlay values are combined into a single list, deduplicated by value, preserving first-occurrence order.\n");
    out.push_str("- **OR**: Any `Some(true)` wins permanently. Once strict mode is enabled by any recipe in the chain, it cannot be disabled.\n");
    out.push_str("- **Last-Some-wins**: The last recipe that specifies a value (`Some(x)`) wins. `None` (field omitted) preserves the earlier value.\n");
    out.push_str(
        "- **Overlay**: The later recipe's value replaces the earlier one entirely if present.\n",
    );

    std::fs::write(out_dir.join("merge.md"), &out)?;
    eprintln!("  Generated merge.md");
    Ok(())
}

// ---------------------------------------------------------------------------
// Built-in recipes
// ---------------------------------------------------------------------------

fn generate_builtin_recipes(out_dir: &Path) -> Result<()> {
    let recipes_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.join("recipes"))
        .context("Could not find recipes directory")?;

    let mut out = String::new();
    out.push_str("# Built-in Recipes\n\n");
    out.push_str("> **This file is auto-generated by `can-docgen`.** Do not edit manually.\n\n");
    out.push_str("Canister ships with the following recipe files in the `recipes/` directory.\n");
    out.push_str("The `base.toml` and `default.toml` recipes are embedded in the binary.\n\n");

    // Read all .toml files from recipes/
    let mut entries: Vec<_> = std::fs::read_dir(&recipes_dir)?
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path().extension().is_some_and(|ext| ext == "toml")
                && e.file_name() != "checksums.toml"
        })
        .collect();
    entries.sort_by_key(|e| e.file_name());

    // Summary table
    out.push_str("## Overview\n\n");
    out.push_str("| Recipe | Description | Auto-detected |\n");
    out.push_str("|--------|-------------|---------------|\n");

    for entry in &entries {
        let content = std::fs::read_to_string(entry.path())?;
        let name = entry
            .path()
            .file_stem()
            .unwrap()
            .to_string_lossy()
            .to_string();

        // Try to parse recipe metadata
        let (description, match_prefix) =
            if let Ok(recipe) = can_policy::RecipeFile::parse(&content) {
                let desc = recipe.description().to_string();
                let prefixes = recipe.match_prefixes().to_vec();
                (
                    if desc.is_empty() {
                        "—".to_string()
                    } else {
                        desc
                    },
                    if prefixes.is_empty() {
                        "No".to_string()
                    } else {
                        format!("Yes (`{}`)", prefixes.join("`, `"))
                    },
                )
            } else {
                // default.toml uses absolute syscall fields, parse differently
                ("—".to_string(), "No".to_string())
            };

        out.push_str(&format!(
            "| `{name}.toml` | {description} | {match_prefix} |\n"
        ));
    }
    out.push('\n');

    // Full contents
    out.push_str("## Recipe Contents\n\n");

    for entry in &entries {
        let content = std::fs::read_to_string(entry.path())?;
        let name = entry
            .path()
            .file_stem()
            .unwrap()
            .to_string_lossy()
            .to_string();

        out.push_str(&format!("### `{name}.toml`\n\n"));
        out.push_str("```toml\n");
        out.push_str(&content);
        if !content.ends_with('\n') {
            out.push('\n');
        }
        out.push_str("```\n\n");
    }

    std::fs::write(out_dir.join("recipes.md"), &out)?;
    eprintln!("  Generated recipes.md");
    Ok(())
}

// ---------------------------------------------------------------------------
// CLI reference
// ---------------------------------------------------------------------------

fn generate_cli_reference(out_dir: &Path) -> Result<()> {
    let mut out = String::new();
    out.push_str("# CLI Reference\n\n");
    out.push_str("> **This file is auto-generated by `can-docgen`.** Do not edit manually.\n\n");

    // Try to find the `can` binary
    let can_bin = find_can_binary();

    match can_bin {
        Some(bin) => {
            // Main help
            out.push_str("## `can`\n\n");
            if let Ok(help) = get_help(&bin, &[]) {
                out.push_str("```\n");
                out.push_str(&help);
                out.push_str("```\n\n");
            }

            // Subcommands
            let subcommands = ["run", "up", "check", "setup", "recipe", "init", "update"];
            for cmd in &subcommands {
                out.push_str(&format!("## `can {cmd}`\n\n"));
                if let Ok(help) = get_help(&bin, &[cmd]) {
                    out.push_str("```\n");
                    out.push_str(&help);
                    out.push_str("```\n\n");
                }
            }

            // Recipe subcommands
            let recipe_subcommands = ["list", "show"];
            for cmd in &recipe_subcommands {
                out.push_str(&format!("## `can recipe {cmd}`\n\n"));
                if let Ok(help) = get_help(&bin, &["recipe", cmd]) {
                    out.push_str("```\n");
                    out.push_str(&help);
                    out.push_str("```\n\n");
                }
            }
        }
        None => {
            out.push_str("*CLI help could not be generated — `can` binary not found.*\n");
            out.push_str("*Build with `cargo build` first, then re-run `can-docgen`.*\n\n");
        }
    }

    std::fs::write(out_dir.join("cli.md"), &out)?;
    eprintln!("  Generated cli.md");
    Ok(())
}

fn find_can_binary() -> Option<PathBuf> {
    // Check target/release, target/debug, then PATH
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir.parent()?.parent()?;

    for profile in &["release", "debug"] {
        let candidate = workspace_root.join("target").join(profile).join("can");
        if candidate.is_file() {
            return Some(candidate);
        }
    }

    // Fallback: check PATH
    which("can")
}

fn which(name: &str) -> Option<PathBuf> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths).find_map(|dir| {
            let candidate = dir.join(name);
            if candidate.is_file() {
                Some(candidate)
            } else {
                None
            }
        })
    })
}

fn get_help(bin: &Path, args: &[&str]) -> Result<String> {
    let mut cmd = Command::new(bin);
    for arg in args {
        cmd.arg(arg);
    }
    cmd.arg("--help");

    let output = cmd.output().context("Failed to run can binary")?;
    if !output.status.success() {
        bail!(
            "can --help failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}
