//! AppArmor profile setup for Canister.
//!
//! On Ubuntu 24.04+ with `kernel.apparmor_restrict_unprivileged_userns=1`,
//! processes in unprivileged user namespaces transition to the `unprivileged_userns`
//! AppArmor profile which denies all capabilities (including mount and chroot).
//!
//! Canister needs a dedicated AppArmor profile (like bubblewrap) that grants
//! mount, pivot_root, and capability permissions to the `can` binary, while
//! ensuring sandboxed child processes remain restricted.
//!
//! This module handles:
//! - Generating a profile with the correct binary path
//! - Detecting if the profile is already installed/loaded
//! - Installing/removing the profile (requires root)

use std::path::{Path, PathBuf};

/// AppArmor profile name used by Canister.
pub const PROFILE_NAME: &str = "canister";

/// Where the profile is installed in the AppArmor configuration directory.
pub const PROFILE_PATH: &str = "/etc/apparmor.d/canister";

/// The template for the AppArmor profile.
/// `{bin_path}` is replaced with the actual binary path.
const PROFILE_TEMPLATE: &str = r#"# Canister sandbox AppArmor profile
# Generated by: can setup
# Binary: {bin_path}
#
# This profile grants the `can` binary permission to use mount, pivot_root,
# and specific capabilities inside unprivileged user namespaces.
#
# To remove: can setup --remove
#   or: sudo rm /etc/apparmor.d/canister && sudo apparmor_parser -R canister

abi <abi/4.0>,

include <tunables/global>

profile canister {bin_path} flags=(attach_disconnected) {
  # Grant only the specific capabilities needed for namespace + filesystem setup.
  allow capability sys_admin,
  allow capability net_admin,
  allow capability sys_chroot,
  allow capability dac_override,
  allow capability dac_read_search,

  allow file rwlkm /{**,},
  allow network,
  allow unix,
  allow signal,
  allow ptrace,
  allow userns,
  allow mount,
  allow umount,
  allow pivot_root,
  allow mqueue,
  allow io_uring,

  # Sandboxed children get restricted sub-profile
  allow px /** -> canister//&canister_sandboxed,

  include if exists <local/canister>
}

profile canister_sandboxed flags=(attach_disconnected) {
  allow file rwlkm /{**,},
  allow network,
  allow unix,
  allow signal,
  allow mqueue,
  allow io_uring,

  allow pix /** -> &canister_sandboxed,

  audit deny capability,
  audit deny mount,
  audit deny umount,
  audit deny pivot_root,
  audit deny userns,
  audit deny ptrace,
  deny dbus,

  include if exists <local/canister_sandboxed>
}
"#;

/// Status of the Canister AppArmor profile.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProfileStatus {
    /// AppArmor doesn't restrict unprivileged user namespaces — no profile needed.
    NotNeeded,
    /// Profile is not installed; filesystem isolation is blocked.
    NotInstalled,
    /// Profile is installed and loaded in enforce mode.
    Installed { bin_path: String },
    /// Profile is installed but for a different binary path.
    WrongPath {
        installed_path: String,
        current_path: String,
    },
}

/// Detect the current status of the Canister AppArmor profile.
pub fn detect_profile_status() -> ProfileStatus {
    // If AppArmor doesn't restrict user namespaces, no profile is needed.
    if !apparmor_restricts_userns() {
        return ProfileStatus::NotNeeded;
    }

    // Check if the profile file exists.
    let profile_path = Path::new(PROFILE_PATH);
    if !profile_path.exists() {
        return ProfileStatus::NotInstalled;
    }

    // Read the installed profile to check the binary path.
    let content = match std::fs::read_to_string(profile_path) {
        Ok(c) => c,
        Err(_) => return ProfileStatus::NotInstalled,
    };

    // Extract the binary path from the installed profile.
    let installed_path = extract_bin_path(&content);

    // Get the current binary path.
    let current_path = current_bin_path();

    match (installed_path, current_path) {
        (Some(installed), Some(current)) if installed == current => {
            // Check if the profile is actually loaded in the kernel.
            if is_profile_loaded() {
                ProfileStatus::Installed {
                    bin_path: installed,
                }
            } else {
                // File exists but profile not loaded — needs reload.
                ProfileStatus::NotInstalled
            }
        }
        (Some(installed), Some(current)) => ProfileStatus::WrongPath {
            installed_path: installed,
            current_path: current,
        },
        _ => ProfileStatus::NotInstalled,
    }
}

/// Generate the AppArmor profile content for the given binary path.
pub fn generate_profile(bin_path: &str) -> String {
    PROFILE_TEMPLATE.replace("{bin_path}", bin_path)
}

/// Get the canonical path to the current `can` binary.
pub fn current_bin_path() -> Option<String> {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.canonicalize().ok())
        .map(|p| p.display().to_string())
}

/// Resolve a binary name to its installed path.
/// First checks if the current exe is the right one, then falls back to PATH lookup.
pub fn resolve_bin_path() -> Option<String> {
    // First: current executable.
    if let Some(path) = current_bin_path() {
        return Some(path);
    }

    // Fallback: look up `can` in PATH.
    if let Ok(path_var) = std::env::var("PATH") {
        for dir in path_var.split(':') {
            let candidate = PathBuf::from(dir).join("can");
            if candidate.exists() {
                if let Ok(canonical) = candidate.canonicalize() {
                    return Some(canonical.display().to_string());
                }
            }
        }
    }

    None
}

/// Check if AppArmor restricts unprivileged user namespaces.
pub fn apparmor_restricts_userns() -> bool {
    std::fs::read_to_string("/proc/sys/kernel/apparmor_restrict_unprivileged_userns")
        .map(|c| c.trim() == "1")
        .unwrap_or(false)
}

/// Check if the canister profile is loaded in the kernel.
fn is_profile_loaded() -> bool {
    // Check /sys/kernel/security/apparmor/policy/profiles/ for canister.*
    let profiles_dir = Path::new("/sys/kernel/security/apparmor/policy/profiles");
    if !profiles_dir.exists() {
        return false;
    }

    if let Ok(entries) = std::fs::read_dir(profiles_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str.starts_with("canister.") {
                // Check if it's in enforce mode.
                let mode_path = entry.path().join("mode");
                if let Ok(mode) = std::fs::read_to_string(&mode_path) {
                    if mode.trim() == "enforce" {
                        return true;
                    }
                }
            }
        }
    }

    false
}

/// Extract the binary path from an installed profile's content.
fn extract_bin_path(content: &str) -> Option<String> {
    // Look for "profile canister /path/to/can"
    for line in content.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("profile canister ") {
            // The path is everything up to "flags=" or end of line.
            let path = rest.split("flags=").next().unwrap_or(rest).trim();
            if path.starts_with('/') {
                return Some(path.to_string());
            }
        }
    }
    None
}

/// Install the AppArmor profile.
///
/// This writes the profile to `/etc/apparmor.d/canister` and loads it.
/// Must be run as root (typically via `sudo can setup`).
///
/// Returns the commands that need to be run if we don't have write access.
pub fn install_profile(bin_path: &str) -> Result<(), SetupError> {
    let content = generate_profile(bin_path);

    // Try to write the profile directly.
    match std::fs::write(PROFILE_PATH, &content) {
        Ok(()) => {
            tracing::info!(path = PROFILE_PATH, "AppArmor profile written");
        }
        Err(e) if e.kind() == std::io::ErrorKind::PermissionDenied => {
            return Err(SetupError::NeedsSudo {
                profile_content: content,
                bin_path: bin_path.to_string(),
            });
        }
        Err(e) => {
            return Err(SetupError::WriteProfile {
                path: PROFILE_PATH.to_string(),
                source: e,
            });
        }
    }

    // Load the profile into the kernel.
    reload_profile()?;

    Ok(())
}

/// Remove the AppArmor profile.
///
/// Must be run as root.
pub fn remove_profile() -> Result<(), SetupError> {
    let profile_path = Path::new(PROFILE_PATH);
    if !profile_path.exists() {
        return Err(SetupError::NotInstalled);
    }

    // Remove the profile from the kernel first.
    let output = std::process::Command::new("apparmor_parser")
        .args(["-R", PROFILE_PATH])
        .output()
        .map_err(|e| SetupError::Command {
            cmd: "apparmor_parser -R".to_string(),
            source: e,
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        tracing::warn!(%stderr, "apparmor_parser -R failed (profile may not have been loaded)");
    }

    // Remove the profile file.
    std::fs::remove_file(profile_path).map_err(|e| SetupError::WriteProfile {
        path: PROFILE_PATH.to_string(),
        source: e,
    })?;

    tracing::info!("AppArmor profile removed");
    Ok(())
}

/// Reload the AppArmor profile into the kernel.
fn reload_profile() -> Result<(), SetupError> {
    let output = std::process::Command::new("apparmor_parser")
        .args(["-r", PROFILE_PATH])
        .output()
        .map_err(|e| SetupError::Command {
            cmd: "apparmor_parser -r".to_string(),
            source: e,
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(SetupError::ProfileLoad {
            stderr: stderr.to_string(),
        });
    }

    tracing::info!("AppArmor profile loaded");
    Ok(())
}

/// Errors from setup operations.
#[derive(Debug, thiserror::Error)]
pub enum SetupError {
    #[error(
        "permission denied — run with sudo:\n\n  \
         sudo can setup\n\n  \
         Or install manually:\n  \
         sudo tee {path} << 'EOF'\n{profile_content}\nEOF\n  \
         sudo apparmor_parser -r {path}",
        path = PROFILE_PATH,
        profile_content = profile_content,
    )]
    NeedsSudo {
        profile_content: String,
        bin_path: String,
    },

    #[error("failed to write profile to {path}: {source}")]
    WriteProfile {
        path: String,
        source: std::io::Error,
    },

    #[error("failed to run {cmd}: {source}")]
    Command { cmd: String, source: std::io::Error },

    #[error("apparmor_parser failed to load profile:\n{stderr}")]
    ProfileLoad { stderr: String },

    #[error("canister AppArmor profile is not installed")]
    NotInstalled,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_profile_contains_binary_path() {
        let profile = generate_profile("/usr/local/bin/can");
        assert!(profile.contains("profile canister /usr/local/bin/can flags="));
        assert!(profile.contains("allow mount,"));
        assert!(profile.contains("allow pivot_root,"));
        assert!(profile.contains("allow capability sys_admin,"));
        assert!(profile.contains("allow capability net_admin,"));
    }

    #[test]
    fn generate_profile_has_sandboxed_subprofile() {
        let profile = generate_profile("/usr/bin/can");
        assert!(profile.contains("profile canister_sandboxed"));
        assert!(profile.contains("audit deny capability,"));
        assert!(profile.contains("audit deny mount,"));
        assert!(profile.contains("audit deny umount,"));
        assert!(profile.contains("audit deny pivot_root,"));
        assert!(profile.contains("audit deny userns,"));
        assert!(profile.contains("audit deny ptrace,"));
        assert!(profile.contains("deny dbus,"));
    }

    #[test]
    fn extract_bin_path_from_generated_profile() {
        let profile = generate_profile("/opt/canister/bin/can");
        let extracted = extract_bin_path(&profile);
        assert_eq!(extracted.as_deref(), Some("/opt/canister/bin/can"));
    }

    #[test]
    fn extract_bin_path_returns_none_for_empty() {
        let extracted = extract_bin_path("");
        assert_eq!(extracted, None);
    }

    #[test]
    fn extract_bin_path_returns_none_for_no_match() {
        let extracted = extract_bin_path("some random content\nwith multiple lines\n");
        assert_eq!(extracted, None);
    }

    #[test]
    fn generate_profile_braces_are_valid_apparmor() {
        let profile = generate_profile("/usr/bin/can");
        // AppArmor profile blocks use single { } not {{ }}
        assert!(!profile.contains("{{"));
        assert!(!profile.contains("}}"));
        // But should have { and }
        assert!(profile.contains('{'));
        assert!(profile.contains('}'));
    }

    #[test]
    fn current_bin_path_returns_some() {
        // In test context, this should return the test binary path.
        let path = current_bin_path();
        assert!(path.is_some());
    }
}
