//! AppArmor MAC backend for Canister.
//!
//! On Ubuntu 24.04+ with `kernel.apparmor_restrict_unprivileged_userns=1`,
//! processes in unprivileged user namespaces transition to the `unprivileged_userns`
//! AppArmor profile which denies all capabilities (including mount and chroot).
//!
//! Canister needs a dedicated AppArmor profile (like bubblewrap) that grants
//! mount, pivot_root, and capability permissions to the `can` binary, while
//! ensuring sandboxed child processes remain restricted.
//!
//! This module handles:
//! - Generating a profile with the correct binary path
//! - Detecting if the profile is already installed/loaded
//! - Installing/removing the profile (requires root)

use std::path::Path;

use super::{MACBackend, MACSystem, PolicyStatus, SetupError};

/// AppArmor profile name used by Canister.
pub const PROFILE_NAME: &str = "canister";

/// Where the profile is installed in the AppArmor configuration directory.
pub const PROFILE_PATH: &str = "/etc/apparmor.d/canister";

/// The template for the AppArmor profile.
/// `{bin_path}` is replaced with the actual binary path.
const PROFILE_TEMPLATE: &str = r#"# Canister sandbox AppArmor profile
# Generated by: can setup
# Binary: {bin_path}
#
# This profile grants the `can` binary permission to use mount, pivot_root,
# and specific capabilities inside unprivileged user namespaces.
#
# To remove: can setup --remove
#   or: sudo rm /etc/apparmor.d/canister && sudo apparmor_parser -R canister

abi <abi/4.0>,

include <tunables/global>

profile canister {bin_path} flags=(attach_disconnected) {
  # Grant only the specific capabilities needed for namespace + filesystem setup.
  allow capability sys_admin,
  allow capability net_admin,
  allow capability sys_chroot,
  allow capability sys_ptrace,
  allow capability dac_override,
  allow capability dac_read_search,

  allow file rwlkm /{**,},
  allow network,
  allow unix,
  allow signal,
  allow ptrace,
  allow userns,
  allow mount,
  allow umount,
  allow pivot_root,
  allow mqueue,
  allow io_uring,

  # Sandboxed children get restricted sub-profile
  allow px /** -> canister//&canister_sandboxed,

  # apparmor_parser must run unconfined to load/unload profiles during setup.
  allow ux /usr/sbin/apparmor_parser,
  allow ux /sbin/apparmor_parser,

  # pasta (network backend) must run unconfined because it needs CAP_SYS_ADMIN
  # to call setns(CLONE_NEWUSER) — the kernel requires this capability to join
  # user namespaces. The canister_sandboxed sub-profile denies sys_admin (which
  # is correct for sandboxed commands), but pasta needs it for legitimate
  # namespace setup. pasta is a trusted system binary from the passt package.
  #
  # pasta dispatches to an AVX2-optimized variant (pasta.avx2) on supported
  # CPUs, so both paths need unconfined exec rules.
  allow ux /usr/bin/pasta,
  allow ux /usr/bin/pasta.avx2,
  allow ux /bin/pasta,
  allow ux /bin/pasta.avx2,

  include if exists <local/canister>
}

profile canister_sandboxed flags=(attach_disconnected) {
  allow file rwlkm /{**,},
  allow network,
  allow unix,
  allow signal,
  allow mqueue,
  allow io_uring,

  allow pix /** -> &canister_sandboxed,

  # Allow the seccomp supervisor (running under the canister profile as PID 1)
  # to read sandboxed process memory via /proc/<pid>/mem. This is required for
  # the USER_NOTIF supervisor to inspect syscall arguments (connect addresses,
  # execve paths, etc.).
  allow ptrace (readby tracedby) peer=canister,
  audit deny ptrace (read trace),

  # Deny all dangerous capabilities and operations for sandboxed processes.
  audit deny capability,
  audit deny mount,
  audit deny umount,
  audit deny pivot_root,
  audit deny userns,
  deny dbus,

  include if exists <local/canister_sandboxed>
}
"#;

/// The AppArmor MAC backend.
pub struct AppArmorBackend;

impl MACBackend for AppArmorBackend {
    fn name(&self) -> &'static str {
        "AppArmor"
    }

    fn system(&self) -> MACSystem {
        MACSystem::AppArmor
    }

    fn is_active(&self) -> bool {
        is_enabled()
    }

    fn restricts_userns(&self) -> bool {
        apparmor_restricts_userns()
    }

    fn policy_status(&self) -> PolicyStatus {
        detect_profile_status()
    }

    fn generate_policy(&self, bin_path: &str) -> String {
        generate_profile(bin_path)
    }

    fn install_policy(&self, bin_path: &str) -> Result<(), SetupError> {
        install_profile(bin_path)
    }

    fn remove_policy(&self) -> Result<(), SetupError> {
        remove_profile()
    }

    fn policy_path(&self) -> &str {
        PROFILE_PATH
    }
}

/// Check if AppArmor is enabled on this kernel.
pub fn is_enabled() -> bool {
    std::fs::read_to_string("/sys/module/apparmor/parameters/enabled")
        .map(|c| c.trim() == "Y")
        .unwrap_or(false)
}

/// Check if AppArmor restricts unprivileged user namespaces.
pub fn apparmor_restricts_userns() -> bool {
    std::fs::read_to_string("/proc/sys/kernel/apparmor_restrict_unprivileged_userns")
        .map(|c| c.trim() == "1")
        .unwrap_or(false)
}

/// Detect the current status of the Canister AppArmor profile.
pub fn detect_profile_status() -> PolicyStatus {
    // If AppArmor doesn't restrict user namespaces, no profile is needed.
    if !apparmor_restricts_userns() {
        return PolicyStatus::NotNeeded;
    }

    // Check if the profile file exists.
    let profile_path = Path::new(PROFILE_PATH);
    if !profile_path.exists() {
        return PolicyStatus::NotInstalled;
    }

    // Read the installed profile to check the binary path.
    let content = match std::fs::read_to_string(profile_path) {
        Ok(c) => c,
        Err(_) => return PolicyStatus::NotInstalled,
    };

    // Extract the binary path from the installed profile.
    let installed_path = extract_bin_path(&content);

    // Get the current binary path.
    let current_path = super::current_bin_path();

    match (installed_path, current_path) {
        (Some(installed), Some(current)) if installed == current => {
            // Check if the profile is actually loaded in the kernel.
            if !is_profile_loaded() {
                return PolicyStatus::NotInstalled;
            }

            // Check if the installed content matches what we'd generate.
            let expected = generate_profile(&installed);
            if content.trim() != expected.trim() {
                return PolicyStatus::Stale {
                    bin_path: installed,
                };
            }

            PolicyStatus::Installed {
                bin_path: installed,
            }
        }
        (Some(installed), Some(current)) => PolicyStatus::WrongPath {
            installed_path: installed,
            current_path: current,
        },
        _ => PolicyStatus::NotInstalled,
    }
}

/// Generate the AppArmor profile content for the given binary path.
pub fn generate_profile(bin_path: &str) -> String {
    PROFILE_TEMPLATE.replace("{bin_path}", bin_path)
}

/// Check if the canister profile is loaded in the kernel.
fn is_profile_loaded() -> bool {
    let profiles_dir = Path::new("/sys/kernel/security/apparmor/policy/profiles");
    if !profiles_dir.exists() {
        return false;
    }

    if let Ok(entries) = std::fs::read_dir(profiles_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str.starts_with("canister.") {
                // Check if it's in enforce mode.
                let mode_path = entry.path().join("mode");
                if let Ok(mode) = std::fs::read_to_string(&mode_path) {
                    if mode.trim() == "enforce" {
                        return true;
                    }
                }
            }
        }
    }

    false
}

/// Extract the binary path from an installed profile's content.
fn extract_bin_path(content: &str) -> Option<String> {
    for line in content.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("profile canister ") {
            let path = rest.split("flags=").next().unwrap_or(rest).trim();
            if path.starts_with('/') {
                return Some(path.to_string());
            }
        }
    }
    None
}

/// Install the AppArmor profile.
///
/// Writes the profile to `/etc/apparmor.d/canister` and loads it.
/// Must be run as root (typically via `sudo can setup`).
fn install_profile(bin_path: &str) -> Result<(), SetupError> {
    let content = generate_profile(bin_path);

    // Try to write the profile directly.
    match std::fs::write(PROFILE_PATH, &content) {
        Ok(()) => {
            tracing::info!(path = PROFILE_PATH, "AppArmor profile written");
        }
        Err(e) if e.kind() == std::io::ErrorKind::PermissionDenied => {
            return Err(SetupError::NeedsSudo {
                policy_content: content.clone(),
                bin_path: bin_path.to_string(),
                manual_instructions: format!(
                    "  sudo tee {PROFILE_PATH} << 'EOF'\n{content}EOF\n  \
                     sudo apparmor_parser -r {PROFILE_PATH}"
                ),
            });
        }
        Err(e) => {
            return Err(SetupError::WritePolicy {
                path: PROFILE_PATH.to_string(),
                source: e,
            });
        }
    }

    // Load the profile into the kernel.
    reload_profile()?;

    Ok(())
}

/// Remove the AppArmor profile.
fn remove_profile() -> Result<(), SetupError> {
    let profile_path = Path::new(PROFILE_PATH);
    if !profile_path.exists() {
        return Err(SetupError::NotInstalled);
    }

    // Remove the profile from the kernel first.
    let output = std::process::Command::new("apparmor_parser")
        .args(["-R", PROFILE_PATH])
        .output()
        .map_err(|e| SetupError::Command {
            cmd: "apparmor_parser -R".to_string(),
            source: e,
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        tracing::warn!(%stderr, "apparmor_parser -R failed (profile may not have been loaded)");
    }

    // Remove the profile file.
    std::fs::remove_file(profile_path).map_err(|e| SetupError::WritePolicy {
        path: PROFILE_PATH.to_string(),
        source: e,
    })?;

    tracing::info!("AppArmor profile removed");
    Ok(())
}

/// Reload the AppArmor profile into the kernel.
fn reload_profile() -> Result<(), SetupError> {
    let output = std::process::Command::new("apparmor_parser")
        .args(["-r", PROFILE_PATH])
        .output()
        .map_err(|e| SetupError::Command {
            cmd: "apparmor_parser -r".to_string(),
            source: e,
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);

        // When the canister AppArmor profile is already loaded, exec'ing
        // apparmor_parser triggers the `px /**` rule, confining it under
        // canister_sandboxed which denies the capabilities it needs.
        // The new profile has a `ux` rule for apparmor_parser, but the
        // OLD (currently loaded) profile doesn't. Detect this and give
        // the user a one-time workaround.
        if stderr.contains("Access denied") || stderr.contains("policy admin privileges") {
            return Err(SetupError::ToolFailed {
                tool: "apparmor_parser".to_string(),
                stderr: format!(
                    "{}\n\n\
                     The currently loaded AppArmor profile is blocking apparmor_parser.\n\
                     This is a one-time issue when upgrading from an older profile.\n\n\
                     Fix: manually reload the profile:\n\
                     \n  sudo apparmor_parser -r {PROFILE_PATH}\n\n\
                     The new profile file has already been written. After reloading,\n\
                     future `can setup` runs will work automatically.",
                    stderr.trim()
                ),
            });
        }

        return Err(SetupError::ToolFailed {
            tool: "apparmor_parser".to_string(),
            stderr: stderr.to_string(),
        });
    }

    tracing::info!("AppArmor profile loaded");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_profile_contains_binary_path() {
        let profile = generate_profile("/usr/local/bin/can");
        assert!(profile.contains("profile canister /usr/local/bin/can flags="));
        assert!(profile.contains("allow mount,"));
        assert!(profile.contains("allow pivot_root,"));
        assert!(profile.contains("allow capability sys_admin,"));
        assert!(profile.contains("allow capability net_admin,"));
    }

    #[test]
    fn generate_profile_has_sandboxed_subprofile() {
        let profile = generate_profile("/usr/bin/can");
        assert!(profile.contains("profile canister_sandboxed"));
        assert!(profile.contains("audit deny capability,"));
        assert!(profile.contains("audit deny mount,"));
        assert!(profile.contains("audit deny umount,"));
        assert!(profile.contains("audit deny pivot_root,"));
        assert!(profile.contains("audit deny userns,"));
        assert!(profile.contains("allow ptrace (readby tracedby) peer=canister,"));
        assert!(profile.contains("audit deny ptrace (read trace),"));
        assert!(profile.contains("deny dbus,"));
        // Verify ux rules for pasta and apparmor_parser
        assert!(profile.contains("allow ux /usr/bin/pasta,"));
        assert!(profile.contains("allow ux /usr/bin/pasta.avx2,"));
        assert!(profile.contains("allow ux /usr/sbin/apparmor_parser,"));
    }

    #[test]
    fn extract_bin_path_from_generated_profile() {
        let profile = generate_profile("/opt/canister/bin/can");
        let extracted = extract_bin_path(&profile);
        assert_eq!(extracted.as_deref(), Some("/opt/canister/bin/can"));
    }

    #[test]
    fn extract_bin_path_returns_none_for_empty() {
        let extracted = extract_bin_path("");
        assert_eq!(extracted, None);
    }

    #[test]
    fn extract_bin_path_returns_none_for_no_match() {
        let extracted = extract_bin_path("some random content\nwith multiple lines\n");
        assert_eq!(extracted, None);
    }

    #[test]
    fn generate_profile_braces_are_valid_apparmor() {
        let profile = generate_profile("/usr/bin/can");
        assert!(!profile.contains("{{"));
        assert!(!profile.contains("}}"));
        assert!(profile.contains('{'));
        assert!(profile.contains('}'));
    }

    #[test]
    fn backend_name() {
        let backend = AppArmorBackend;
        assert_eq!(backend.name(), "AppArmor");
        assert_eq!(backend.system(), MACSystem::AppArmor);
    }
}
