//! SELinux MAC backend for Canister.
//!
//! On Fedora 41+ and RHEL 10+, SELinux restricts unprivileged user namespace
//! creation via the `user_namespace { create }` permission. Processes need a
//! policy module that grants the required types and permissions.
//!
//! Canister's SELinux policy defines:
//! - `canister_t` — domain for the `can` binary (full sandbox capabilities)
//! - `canister_sandboxed_t` — domain for sandboxed child processes (restricted)
//! - `canister_exec_t` — file type for the `can` binary (triggers domain transition)
//!
//! Installation requires the refpolicy development Makefile and `semodule`
//! (provided by `selinux-policy-devel` and `policycoreutils` packages).

use std::path::Path;

use super::{MACBackend, MACSystem, PolicyStatus, SetupError};

/// SELinux module name.
pub const MODULE_NAME: &str = "canister";

/// Directory where SELinux policy source files are written during install.
const POLICY_DIR: &str = "/tmp/canister-selinux";

/// Where the compiled policy module is cached for reference.
const POLICY_REF_PATH: &str = "/etc/canister/selinux/canister.te";

/// Path to the reference policy Makefile (provided by selinux-policy-devel).
/// This handles m4 macro expansion, checkmodule compilation, and packaging.
const REFPOLICY_MAKEFILE: &str = "/usr/share/selinux/devel/Makefile";

/// The SELinux type enforcement policy template.
/// `{bin_path}` is replaced with the actual binary path.
const TE_TEMPLATE: &str = r#"# Canister sandbox SELinux policy module
# Generated by: can setup
# Binary: {bin_path}

policy_module(canister, 1.0.0)

require {
    type unconfined_t;
    role unconfined_r;
    attribute file_type;
    attribute exec_type;
    attribute domain;
    type proc_t;
    type fs_t;
    type tmpfs_t;
}

########################################
# Type declarations
########################################

# Domain for the can binary (sandbox supervisor).
type canister_t;
type canister_exec_t;
domain_type(canister_t)
domain_entry_file(canister_t, canister_exec_t)

# Restricted domain for sandboxed child processes.
type canister_sandboxed_t;
domain_type(canister_sandboxed_t)

# Programmatic domain transition: the supervisor uses setexeccon() before exec
# to place children into canister_sandboxed_t. No automatic type_transition rule
# is needed — this avoids depending on specific file types like bin_t.
allow canister_t canister_sandboxed_t:process { transition dyntransition };
allow canister_t self:process { setexec };

# NNP (No New Privileges) transition — required when the child has
# PR_SET_NO_NEW_PRIVS set, which is common in sandbox environments.
allow canister_t canister_sandboxed_t:process2 { nnp_transition nosuid_transition };

# Any executable file type can be an entry point for the sandboxed domain.
allow canister_sandboxed_t exec_type:file entrypoint;

# Allow users to transition into canister_t by executing the can binary.
role unconfined_r types canister_t;
role unconfined_r types canister_sandboxed_t;

# Allow unconfined_t to transition to canister_t.
allow unconfined_t canister_t:process { transition dyntransition };
allow unconfined_t canister_t:process2 { nnp_transition nosuid_transition };

########################################
# canister_t — full sandbox supervisor permissions
########################################

# User namespace creation (Fedora 41+ restricts this).
allow canister_t self:user_namespace create;
allow canister_t self:cap_userns { sys_admin sys_ptrace net_admin sys_chroot };

# Standard process capabilities needed for namespace setup.
allow canister_t self:capability { sys_admin net_admin sys_chroot sys_ptrace dac_override dac_read_search };
allow canister_t self:process { fork setexec setpgid setsched signal_perms transition };

# Mount / pivot_root for filesystem isolation.
allow canister_t fs_t:filesystem { mount unmount remount };
allow canister_t self:filesystem { associate mount unmount };
allow canister_t tmpfs_t:filesystem { mount unmount };

# File access (broad — the sandbox supervisor needs to set up mounts).
allow canister_t file_type:file { getattr open read execute execute_no_trans map };
allow canister_t file_type:dir { getattr open read search };
allow canister_t file_type:lnk_file { getattr read };

# /proc access for PID namespace supervision and seccomp USER_NOTIF.
allow canister_t proc_t:file { getattr open read };
allow canister_t canister_sandboxed_t:process { ptrace signal sigkill };
allow canister_t canister_sandboxed_t:file { getattr open read };

# Network: socket operations for pasta coordination and sandboxed networking.
allow canister_t self:tcp_socket { create accept bind connect listen getattr setopt shutdown };
allow canister_t self:udp_socket { create bind connect getattr setopt };
allow canister_t self:unix_stream_socket { create accept bind connect listen getattr setopt };
allow canister_t self:unix_dgram_socket { create bind connect getattr setopt sendto };
allow canister_t self:netlink_route_socket { create bind getattr nlmsg_read };

# Pipe operations (parent-child protocol uses 3 pipes).
allow canister_t self:fifo_file { getattr open read write };
allow canister_t canister_sandboxed_t:fifo_file { getattr open read write };

# Execute binaries (pasta, etc.) without automatic domain transition.
# Uses exec_type attribute to cover all executable file types.
allow canister_t exec_type:file { execute execute_no_trans };

# Seccomp BPF.
allow canister_t self:bpf { prog_load prog_run };

########################################
# canister_sandboxed_t — restricted child domain
########################################

# Basic process operations.
allow canister_sandboxed_t self:process { fork signal_perms setpgid setsched };

# File access (read/execute within the sandbox filesystem).
allow canister_sandboxed_t file_type:file { getattr open read execute execute_no_trans map };
allow canister_sandboxed_t file_type:dir { getattr open read search };
allow canister_sandboxed_t file_type:lnk_file { getattr read };

# Allow sandboxed processes to use inherited network sockets.
allow canister_sandboxed_t self:tcp_socket { create accept bind connect listen getattr setopt shutdown read write };
allow canister_sandboxed_t self:udp_socket { create bind connect getattr setopt read write };
allow canister_sandboxed_t self:unix_stream_socket { create accept bind connect listen getattr setopt read write };
allow canister_sandboxed_t self:unix_dgram_socket { create bind connect getattr setopt sendto read write };

# Pipe and terminal I/O.
allow canister_sandboxed_t self:fifo_file { getattr open read write };
allow canister_sandboxed_t canister_t:fifo_file { getattr read write };

# Allow the supervisor to ptrace sandboxed processes (seccomp USER_NOTIF).
allow canister_sandboxed_t canister_t:process { sigchld };

# Deny namespace creation (the whole point of sandboxing).
# SELinux default-deny handles this — we just don't grant user_namespace or
# capability permissions to canister_sandboxed_t.
"#;

/// File context template.
/// `{bin_path}` is replaced with the actual binary path.
const FC_TEMPLATE: &str = r#"# Canister SELinux file contexts
# Generated by: can setup

{bin_path}    --    system_u:object_r:canister_exec_t:s0
"#;

/// Interface file (empty — no cross-module interfaces needed).
const IF_TEMPLATE: &str = r#"## <summary>Canister sandbox policy</summary>
## <desc>
## <p>
##   Policy for the Canister sandbox tool.
##   No cross-module interfaces are exported.
## </p>
## </desc>
"#;

/// The SELinux MAC backend.
pub struct SELinuxBackend;

impl MACBackend for SELinuxBackend {
    fn name(&self) -> &'static str {
        "SELinux"
    }

    fn system(&self) -> MACSystem {
        MACSystem::SELinux
    }

    fn is_active(&self) -> bool {
        is_enabled()
    }

    fn restricts_userns(&self) -> bool {
        selinux_restricts_userns()
    }

    fn policy_status(&self) -> PolicyStatus {
        detect_module_status()
    }

    fn generate_policy(&self, bin_path: &str) -> String {
        generate_te(bin_path)
    }

    fn install_policy(&self, bin_path: &str) -> Result<(), SetupError> {
        install_module(bin_path)
    }

    fn remove_policy(&self) -> Result<(), SetupError> {
        remove_module()
    }

    fn policy_path(&self) -> &str {
        POLICY_REF_PATH
    }
}

/// Check if SELinux is enabled on this kernel.
pub fn is_enabled() -> bool {
    Path::new("/sys/fs/selinux").exists()
}

/// Check if SELinux is in enforcing mode.
pub fn is_enforcing() -> bool {
    std::fs::read_to_string("/sys/fs/selinux/enforce")
        .map(|c| c.trim() == "1")
        .unwrap_or(false)
}

/// Check if SELinux restricts unprivileged user namespace creation.
///
/// On Fedora 41+, the `nnp_nosuid_transition` and `user_namespace` permissions
/// are used to control user namespace access. We check if the selinux policy
/// is in enforcing mode — if so, user namespaces are restricted for
/// unconfined processes by default on Fedora 41+.
///
/// A more precise check would query `sesearch` for the user_namespace permission,
/// but that requires the setools package which may not be installed.
pub fn selinux_restricts_userns() -> bool {
    // SELinux must be enforcing to restrict anything.
    if !is_enforcing() {
        return false;
    }

    // Check for the Fedora 41+ user namespace restriction.
    // The kernel exposes this via /proc/sys/user/max_user_namespaces being
    // accessible but SELinux denying the actual create operation.
    // The most reliable indicator is the presence of the userns_create boolean.
    let output = std::process::Command::new("getsebool")
        .arg("user_namespace_allowed")
        .output();

    match output {
        Ok(out) if out.status.success() => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            // If the boolean exists and is off, user namespaces are restricted.
            // "user_namespace_allowed --> off"
            stdout.contains("off")
        }
        _ => {
            // Boolean doesn't exist or getsebool not available.
            // On older Fedora/RHEL, SELinux doesn't restrict user namespaces.
            false
        }
    }
}

/// Detect the current status of the canister SELinux module.
fn detect_module_status() -> PolicyStatus {
    if !selinux_restricts_userns() {
        return PolicyStatus::NotNeeded;
    }

    // Check if the module is loaded.
    if !is_module_loaded() {
        return PolicyStatus::NotInstalled;
    }

    // Check if we have a reference copy of the installed TE file.
    let ref_path = Path::new(POLICY_REF_PATH);
    if !ref_path.exists() {
        // Module is loaded but we have no reference — treat as installed
        // (user may have installed manually).
        return PolicyStatus::Installed {
            bin_path: "unknown".to_string(),
        };
    }

    // Read the reference TE and extract the binary path.
    let content = match std::fs::read_to_string(ref_path) {
        Ok(c) => c,
        Err(_) => {
            return PolicyStatus::Installed {
                bin_path: "unknown".to_string(),
            };
        }
    };

    let installed_path = extract_bin_path_from_te(&content);
    let current_path = super::current_bin_path();

    match (installed_path, current_path) {
        (Some(installed), Some(current)) if installed == current => {
            // Check if content matches what we'd generate.
            let expected = generate_te(&installed);
            if content.trim() != expected.trim() {
                PolicyStatus::Stale {
                    bin_path: installed,
                }
            } else {
                PolicyStatus::Installed {
                    bin_path: installed,
                }
            }
        }
        (Some(installed), Some(current)) => PolicyStatus::WrongPath {
            installed_path: installed,
            current_path: current,
        },
        (Some(installed), None) => PolicyStatus::Installed {
            bin_path: installed,
        },
        _ => PolicyStatus::Installed {
            bin_path: "unknown".to_string(),
        },
    }
}

/// Check if the canister SELinux module is loaded.
fn is_module_loaded() -> bool {
    let output = std::process::Command::new("semodule").args(["-l"]).output();

    match output {
        Ok(out) if out.status.success() => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            stdout.lines().any(|line| {
                let name = line.split_whitespace().next().unwrap_or("");
                name == MODULE_NAME
            })
        }
        _ => false,
    }
}

/// Generate the type enforcement policy content.
pub fn generate_te(bin_path: &str) -> String {
    TE_TEMPLATE.replace("{bin_path}", bin_path)
}

/// Generate the file context content.
pub fn generate_fc(bin_path: &str) -> String {
    // SELinux file contexts use regex — escape dots in the path.
    let escaped = bin_path.replace('.', r"\.");
    FC_TEMPLATE.replace("{bin_path}", &escaped)
}

/// Generate the interface file content.
pub fn generate_if() -> String {
    IF_TEMPLATE.to_string()
}

/// Extract binary path from the TE file header comment.
fn extract_bin_path_from_te(content: &str) -> Option<String> {
    for line in content.lines() {
        if let Some(rest) = line.strip_prefix("# Binary: ") {
            let path = rest.trim();
            if path.starts_with('/') {
                return Some(path.to_string());
            }
        }
    }
    None
}

/// Install the SELinux policy module.
///
/// Uses the reference policy build system (`/usr/share/selinux/devel/Makefile`)
/// which handles m4 macro expansion, compilation, and packaging. This is the
/// standard way to build SELinux modules on Fedora/RHEL and requires the
/// `selinux-policy-devel` package.
///
/// Steps:
/// 1. Write .te, .fc, .if to a temp directory
/// 2. Build with the reference policy Makefile (m4 + checkmodule + semodule_package)
/// 3. Install with semodule -i
/// 4. Apply file contexts with restorecon
/// 5. Save reference copy of .te for status detection
fn install_module(bin_path: &str) -> Result<(), SetupError> {
    let te_content = generate_te(bin_path);
    let fc_content = generate_fc(bin_path);
    let if_content = generate_if();

    // Create temp directory for policy source files.
    std::fs::create_dir_all(POLICY_DIR).map_err(|e| SetupError::WritePolicy {
        path: POLICY_DIR.to_string(),
        source: e,
    })?;

    let te_path = format!("{POLICY_DIR}/{MODULE_NAME}.te");
    let fc_path = format!("{POLICY_DIR}/{MODULE_NAME}.fc");
    let if_path = format!("{POLICY_DIR}/{MODULE_NAME}.if");
    let pp_path = format!("{POLICY_DIR}/{MODULE_NAME}.pp");

    // Write source files.
    std::fs::write(&te_path, &te_content).map_err(|e| SetupError::WritePolicy {
        path: te_path.clone(),
        source: e,
    })?;
    std::fs::write(&fc_path, &fc_content).map_err(|e| SetupError::WritePolicy {
        path: fc_path.clone(),
        source: e,
    })?;
    std::fs::write(&if_path, &if_content).map_err(|e| SetupError::WritePolicy {
        path: if_path.clone(),
        source: e,
    })?;

    tracing::info!(dir = POLICY_DIR, "SELinux policy source files written");

    // Build with the reference policy Makefile. This handles:
    // - m4 macro expansion (domain_type, domain_entry_file, etc.)
    // - checkmodule compilation
    // - semodule_package packaging
    let makefile = REFPOLICY_MAKEFILE;
    if !Path::new(makefile).exists() {
        return Err(SetupError::ToolFailed {
            tool: "selinux-policy-devel".to_string(),
            stderr: format!(
                "{makefile} not found.\n\
                 Install the SELinux development tools:\n  \
                 sudo dnf install selinux-policy-devel    # Fedora/RHEL\n  \
                 sudo apt install selinux-policy-dev      # Debian/Ubuntu"
            ),
        });
    }

    let pp_target = format!("{MODULE_NAME}.pp");
    let output = std::process::Command::new("make")
        .args(["-f", makefile, &pp_target])
        .current_dir(POLICY_DIR)
        .output()
        .map_err(|e| SetupError::Command {
            cmd: format!("make -f {makefile}"),
            source: e,
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(SetupError::ToolFailed {
            tool: format!("make -f {makefile}"),
            stderr: stderr.to_string(),
        });
    }

    // Install the compiled module.
    let output = std::process::Command::new("semodule")
        .args(["-i", &pp_path])
        .output()
        .map_err(|e| {
            if e.kind() == std::io::ErrorKind::PermissionDenied {
                SetupError::NeedsSudo {
                    policy_content: te_content.clone(),
                    bin_path: bin_path.to_string(),
                    manual_instructions: format!(
                        "  cd {POLICY_DIR}\n  \
                         sudo make -f {makefile} {pp_target}\n  \
                         sudo semodule -i {pp_path}\n  \
                         sudo restorecon -v {bin_path}"
                    ),
                }
            } else {
                SetupError::Command {
                    cmd: "semodule -i".to_string(),
                    source: e,
                }
            }
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        if stderr.contains("Permission denied") || stderr.contains("Could not start") {
            return Err(SetupError::NeedsSudo {
                policy_content: te_content,
                bin_path: bin_path.to_string(),
                manual_instructions: format!(
                    "  sudo semodule -i {pp_path}\n  \
                     sudo restorecon -v {bin_path}\n\n  \
                     Policy files are in: {POLICY_DIR}/"
                ),
            });
        }
        return Err(SetupError::ToolFailed {
            tool: "semodule -i".to_string(),
            stderr: stderr.to_string(),
        });
    }

    // Apply file contexts.
    let output = std::process::Command::new("restorecon")
        .args(["-v", bin_path])
        .output()
        .map_err(|e| SetupError::Command {
            cmd: "restorecon".to_string(),
            source: e,
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        tracing::warn!(%stderr, "restorecon failed (file context may not be applied)");
    }

    // Save reference copy for status detection.
    let ref_dir = Path::new(POLICY_REF_PATH).parent().unwrap();
    if let Err(e) = std::fs::create_dir_all(ref_dir) {
        tracing::warn!(error = %e, "could not create reference directory (status detection may be limited)");
    } else if let Err(e) = std::fs::write(POLICY_REF_PATH, &te_content) {
        tracing::warn!(error = %e, "could not save reference TE file (status detection may be limited)");
    }

    // Clean up temp files.
    let _ = std::fs::remove_dir_all(POLICY_DIR);

    tracing::info!("SELinux policy module installed");
    Ok(())
}

/// Remove the SELinux policy module.
fn remove_module() -> Result<(), SetupError> {
    if !is_module_loaded() {
        return Err(SetupError::NotInstalled);
    }

    let output = std::process::Command::new("semodule")
        .args(["-r", MODULE_NAME])
        .output()
        .map_err(|e| SetupError::Command {
            cmd: "semodule -r".to_string(),
            source: e,
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(SetupError::ToolFailed {
            tool: "semodule -r".to_string(),
            stderr: stderr.to_string(),
        });
    }

    // Clean up reference file.
    let _ = std::fs::remove_file(POLICY_REF_PATH);
    let ref_dir = Path::new(POLICY_REF_PATH).parent().unwrap();
    let _ = std::fs::remove_dir(ref_dir);

    tracing::info!("SELinux policy module removed");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_te_contains_binary_path_in_comment() {
        let te = generate_te("/usr/local/bin/can");
        assert!(te.contains("# Binary: /usr/local/bin/can"));
    }

    #[test]
    fn generate_te_has_required_types() {
        let te = generate_te("/usr/bin/can");
        assert!(te.contains("type canister_t;"));
        assert!(te.contains("type canister_exec_t;"));
        assert!(te.contains("type canister_sandboxed_t;"));
    }

    #[test]
    fn generate_te_grants_userns_permissions() {
        let te = generate_te("/usr/bin/can");
        assert!(te.contains("user_namespace create"));
        assert!(te.contains("cap_userns"));
    }

    #[test]
    fn generate_te_has_require_block_for_external_types() {
        let te = generate_te("/usr/bin/can");
        assert!(te.contains("require {"));
        assert!(te.contains("type unconfined_t;"));
        assert!(te.contains("attribute exec_type;"));
        assert!(te.contains("attribute file_type;"));
        assert!(te.contains("type proc_t;"));
        assert!(te.contains("type tmpfs_t;"));
    }

    #[test]
    fn generate_te_uses_programmatic_transition() {
        let te = generate_te("/usr/bin/can");
        // setexeccon()-based transition, no type_transition rule needed.
        assert!(te.contains("setexec"));
        assert!(
            te.contains("canister_t canister_sandboxed_t:process { transition dyntransition }")
        );
        assert!(te.contains(
            "canister_t canister_sandboxed_t:process2 { nnp_transition nosuid_transition }"
        ));
        assert!(te.contains("canister_sandboxed_t exec_type:file entrypoint"));
    }

    #[test]
    fn generate_te_does_not_use_bin_t_in_rules() {
        let te = generate_te("/usr/bin/can");
        // bin_t was removed from actual rules — we use exec_type attribute instead.
        // Comments may still mention bin_t for historical context, so only check
        // non-comment lines.
        for line in te.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with('#') || trimmed.is_empty() {
                continue;
            }
            assert!(
                !trimmed.contains("bin_t"),
                "Found bin_t in policy rule: {trimmed}"
            );
        }
    }

    #[test]
    fn generate_fc_escapes_dots() {
        let fc = generate_fc("/usr/local/bin/can.v2");
        assert!(fc.contains(r"/usr/local/bin/can\.v2"));
    }

    #[test]
    fn generate_fc_contains_file_context() {
        let fc = generate_fc("/usr/bin/can");
        assert!(fc.contains("canister_exec_t"));
        assert!(fc.contains("system_u:object_r"));
    }

    #[test]
    fn extract_bin_path_from_te_header() {
        let te = generate_te("/opt/canister/bin/can");
        let extracted = extract_bin_path_from_te(&te);
        assert_eq!(extracted.as_deref(), Some("/opt/canister/bin/can"));
    }

    #[test]
    fn extract_bin_path_from_te_returns_none_for_empty() {
        assert_eq!(extract_bin_path_from_te(""), None);
    }

    #[test]
    fn backend_name() {
        let backend = SELinuxBackend;
        assert_eq!(backend.name(), "SELinux");
        assert_eq!(backend.system(), MACSystem::SELinux);
    }
}
